joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

dm_test_controller:
  type: damiao/DmController
  # 顺序对应 DmController.cpp 里 joints_[0] ~ joints_[4]
  joints:
    - leg_r1_joint
    - leg_r2_joint
    - leg_r3_joint
    - leg_r4_joint
    - leg_r5_joint
    # - leg_l1_joint
    # - leg_l2_joint
    # - leg_l3_joint
    # - leg_l4_joint
    # - leg_l5_joint